In [ ]:
import numpy as np
import pandas as pd

# 소수점 첫 번째 자리까지 표시
pd.set_option('precision', 1)

# 데이터프레임 생성
df_left = pd.DataFrame({'색': ['red', 'orange', 'yellow', 'green', 'blue'],
                        '가격': [1000, 2000, 3000, 4000, 5000]},
                       index=[9, 1, 2, 3, 4])

df_right = pd.DataFrame({'색': ['yellow', 'green', 'blue', 'navy', 'purple'],
                         '이름': ['노란색', '초록색', '파란색', '남색', '보라색']},
                        index=[3, 4, 5, 6, 7])

# 데이터프레임 df_left & df_right 확인
display([df_left, df_right], ['df_left', 'df_right'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색]

['df_left', 'df_right']

In [ ]:
# Inner Join
df_inner = pd.merge(df_left, df_right, on="색", how="inner")

# 데이터 프레임 df_left & df_right, df_inner 확인
display([df_left, df_right, df_inner], ['df_left', 'df_right', 'df_inner'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,         색    가격   이름
 0  yellow  3000  노란색
 1   green  4000  초록색
 2    blue  5000  파란색]

['df_left', 'df_right', 'df_inner']

In [ ]:
# Outer Join
df_outer = pd.merge(df_left, df_right, on="색", how="outer")

# 데이터프레임 df_left & df_right & df_outer 확인
display([df_left, df_right, df_outer], ['df_left', 'df_right', 'df_outer'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,         색      가격   이름
 0     red  1000.0  NaN
 1  orange  2000.0  NaN
 2  yellow  3000.0  노란색
 3   green  4000.0  초록색
 4    blue  5000.0  파란색
 5    navy     NaN   남색
 6  purple     NaN  보라색]

['df_left', 'df_right', 'df_outer']

In [ ]:
# Left Join
df_left_join = pd.merge(df_left, df_right, on="색", how="left")

# 데이터프레임 df_left & df_right, df_left_join 확인
display([df_left, df_right, df_left_join], ['df_left', 'df_right', 'df_left_join'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,         색    가격   이름
 0     red  1000  NaN
 1  orange  2000  NaN
 2  yellow  3000  노란색
 3   green  4000  초록색
 4    blue  5000  파란색]

['df_left', 'df_right', 'df_left_join']

In [ ]:
# Right Join
df_right_merge = pd.merge(df_left, df_right, on="색", how="right")

# 데이터프레임 df_left & df_right, df_right_merge 확인
display([df_left, df_right, df_right_merge], ['df_left', 'df_right', 'df_right_merge'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,         색      가격   이름
 0  yellow  3000.0  노란색
 1   green  4000.0  초록색
 2    blue  5000.0  파란색
 3    navy     NaN   남색
 4  purple     NaN  보라색]

['df_left', 'df_right', 'df_right_merge']

In [ ]:
# Right_Join - 인덱스 기준
df_right_merge_index = pd.merge(df_left, df_right, left_index=True, right_index=True, how="right")

# 데이터프레임 df_left & df_right, df_right_merge_index 확인
display([df_left, df_right, df_right_merge_index], ['df_left', 'df_right', 'df_right_merge_index'])

[        색    가격
 9     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,      색_x      가격     색_y   이름
 3  green  4000.0  yellow  노란색
 4   blue  5000.0   green  초록색
 5    NaN     NaN    blue  파란색
 6    NaN     NaN    navy   남색
 7    NaN     NaN  purple  보라색]

['df_left', 'df_right', 'df_right_merge_index']

In [ ]:
# 데이터 프레임 생성
df_left = pd.DataFrame(
    {'색': ['red', 'orange', 'yellow', 'yellow', 'green', 'blue'],
     '가격': [1000, 2000, 3000, 3000, 4000, 5000]},
     index=[0, 1, 2, 3, 4, 5])

df_right = pd.DataFrame(
    {'색': ['yellow', 'yellow', 'green', 'blue', 'navy', 'purple'],
    '이름': ['노란색', '노란색', '초록색', '파란색', '남색', '보라색']},
    index=[3, 4, 5, 6, 7, 8])

# Inner Join
df_inner = pd.merge(df_left, df_right, on="색", how="inner")

# 데이터프레임 df_left & df_right, df_inner 확인
display([df_left, df_right, df_inner], ['df_left', 'df_right', 'df_inner'])

[        색    가격
 0     red  1000
 1  orange  2000
 2  yellow  3000
 3  yellow  3000
 4   green  4000
 5    blue  5000,         색   이름
 3  yellow  노란색
 4  yellow  노란색
 5   green  초록색
 6    blue  파란색
 7    navy   남색
 8  purple  보라색,         색    가격   이름
 0  yellow  3000  노란색
 1  yellow  3000  노란색
 2  yellow  3000  노란색
 3  yellow  3000  노란색
 4   green  4000  초록색
 5    blue  5000  파란색]

['df_left', 'df_right', 'df_inner']

In [ ]:
# 데이터 프레임 생성
df_left = pd.DataFrame({'색': ['red', 'orange', 'yellow', 'yellow', 'green', 'blue'],
                        '가격': [1000, 2000, 3000, 3000, 4000, 5000]},
                       index=[0, 1, 2, 3, 4, 5])

df_right = pd.DataFrame({'색': ['yellow', 'yellow', 'yellow', 'green', 'blue', 'navy', 'purple'],
                         '이름': ['노란색', '노란색', '노랑', '초록색', '파란색', '남색', '보라색']},
                        index=[6, 7, 8, 9, 10, 11, 12])

# Outer Join
df_outer = pd.merge(df_left, df_right, on="색", how="outer")

# 데이터프레임 df_left & df_right, df_outer 확인
display([df_left, df_right, df_outer], ['df_left', 'df_right', 'df_outer'])

[        색    가격
 0     red  1000
 1  orange  2000
 2  yellow  3000
 3  yellow  3000
 4   green  4000
 5    blue  5000,          색   이름
 6   yellow  노란색
 7   yellow  노란색
 8   yellow   노랑
 9    green  초록색
 10    blue  파란색
 11    navy   남색
 12  purple  보라색,          색      가격   이름
 0      red  1000.0  NaN
 1   orange  2000.0  NaN
 2   yellow  3000.0  노란색
 3   yellow  3000.0  노란색
 4   yellow  3000.0   노랑
 5   yellow  3000.0  노란색
 6   yellow  3000.0  노란색
 7   yellow  3000.0   노랑
 8    green  4000.0  초록색
 9     blue  5000.0  파란색
 10    navy     NaN   남색
 11  purple     NaN  보라색]

['df_left', 'df_right', 'df_outer']

In [ ]:
# df_left, df_right 두 개의 데이터프레임 생성
df_left = pd.DataFrame(
    {'색': ['red', 'orange', 'yellow', 'green', 'blue'],
     '가격': [1000, 2000, 3000, 4000, 5000]},
     index=[0, 1, 2, 3, 4])

df_right = pd.DataFrame(
    {'색': ['yellow', 'green', 'blue', 'navy', 'purple'],
     '이름': ['노란색', '초록색', '파란색', '남색', '보라색']},
     index=[3, 4, 5, 6, 7])

# 데이터프레임 df_left & df_right 확인
display([df_left, df_right], ['df_left', 'df_right'])

# join 으로 데이터프레임 결합
df_right = df_left.join(df_right, how='right')

[        색    가격
 0     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,         색   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색]

['df_left', 'df_right']

ValueError: ignored

In [ ]:
# 인덱스 대신 열(키) 이름으로 데이터를 합칠 경우
df_right_join_key = df_left.join(df_right.set_index(['색'], verify_integrity=True), on=['색'], how='right')

df_right_join_key

          색      가격   이름
2.0  yellow  3000.0  노란색
3.0   green  4000.0  초록색
4.0    blue  5000.0  파란색
NaN    navy     NaN   남색
NaN  purple     NaN  보라색

In [ ]:
# df_left, df_right 두 개의 데이터프레임 생성
df_left = pd.DataFrame({'색_left': ['red', 'orange', 'yellow', 'green', 'blue'],
                        '가격': [1000, 2000, 3000, 4000, 5000]},
                       index=[0, 1, 2, 3, 4])

df_right = pd.DataFrame({'색_right': ['yellow', 'green', 'blue', 'navy', 'purple'],
                         '이름': ['노란색', '초록색', '파란색', '남색', '보라색']},
                        index=[3, 4, 5, 6, 7])

# 인덱스 기준으로 데이터를 합칠 경우
df_right_join = df_left.join(df_right, how='right')

# 데이터 프레임 df_left, df_right, df_right_join index 확인
display([df_left, df_right, df_right_join], ['df_left', 'df_right', 'df_right_join'])

[   색_left    가격
 0     red  1000
 1  orange  2000
 2  yellow  3000
 3   green  4000
 4    blue  5000,   색_right   이름
 3  yellow  노란색
 4   green  초록색
 5    blue  파란색
 6    navy   남색
 7  purple  보라색,   색_left      가격 색_right   이름
 3  green  4000.0  yellow  노란색
 4   blue  5000.0   green  초록색
 5    NaN     NaN    blue  파란색
 6    NaN     NaN    navy   남색
 7    NaN     NaN  purple  보라색]

['df_left', 'df_right', 'df_right_join']

In [11]:
from IPython.display import display
import pandas as pd

# df_left, df_right 두 개의 데이터프레임 생성
df_left = pd.DataFrame({'색_left': ['red', 'orange', 'yellow', 'yellow', 'green', 'blue'],
                        '가격': [1000, 2000, 3000, 3000, 4000, 5000]},
                       index=[0, 1, 2, 3, 4, 5])

df_right = pd.DataFrame({'색_right': ['yellow', 'yellow', 'green', 'blue', 'navy', 'purple'],
                         '이름': ['노란색', '노란색', '초록색', '파란색', '남색', '보라색']},
                        index=[3, 4, 5, 6, 7, 8])

# join을 이용해 두 데이터프레임 합치기 (기본값: 인덱스)
df_right_join_index = df_left.join(df_right, how='right')

# merge를 이용해 두 데이터프레임 합치기 (인덱스 기준 설정)
df_right_merge_index = pd.merge(df_left, df_right, left_index=True, right_index=True, how="right")

# 데이터프레임 및 결괏값 확인
display([df_left, df_right], ['df_left', 'df_right'])
display([df_right_join_index, df_right_merge_index], ['df_right_join_index', 'df_right_merge_index'])

[   색_left    가격
 0     red  1000
 1  orange  2000
 2  yellow  3000
 3  yellow  3000
 4   green  4000
 5    blue  5000,   색_right   이름
 3  yellow  노란색
 4  yellow  노란색
 5   green  초록색
 6    blue  파란색
 7    navy   남색
 8  purple  보라색]

['df_left', 'df_right']

[   색_left      가격 색_right   이름
 3  yellow  3000.0  yellow  노란색
 4   green  4000.0  yellow  노란색
 5    blue  5000.0   green  초록색
 6     NaN     NaN    blue  파란색
 7     NaN     NaN    navy   남색
 8     NaN     NaN  purple  보라색,    색_left      가격 색_right   이름
 3  yellow  3000.0  yellow  노란색
 4   green  4000.0  yellow  노란색
 5    blue  5000.0   green  초록색
 6     NaN     NaN    blue  파란색
 7     NaN     NaN    navy   남색
 8     NaN     NaN  purple  보라색]

['df_right_join_index', 'df_right_merge_index']

In [13]:
df_1 = pd.DataFrame({'색1': ['red', 'orange'],
                     '이름1': ['빨간색', '주황색']},
                     index=[0, 1])

df_2 = pd.DataFrame({'색2': ['yellow', 'green'],
                     '이름2': ['노란색', '초록색']},
                    index=[2, 3])

df_3 = pd.DataFrame({'색3': ['blue', 'navy'],
                     '이름3': ['파란색', '남색']},
                    index=[8, 9])

# 기본값: 행(row) 기준으로 연결
result_row = pd.concat([df_1, df_2, df_3])

# 연결할 데이터프레임 확인
display([df_1, df_2, df_3], ['df_1', 'df_2', 'df_3'])

# 결과 데이터프레임
result_row

[       색1  이름1
 0     red  빨간색
 1  orange  주황색,        색2  이름2
 2  yellow  노란색
 3   green  초록색,      색3  이름3
 8  blue  파란색
 9  navy   남색]

['df_1', 'df_2', 'df_3']

       색1  이름1      색2  이름2    색3  이름3
0     red  빨간색     NaN  NaN   NaN  NaN
1  orange  주황색     NaN  NaN   NaN  NaN
2     NaN  NaN  yellow  노란색   NaN  NaN
3     NaN  NaN   green  초록색   NaN  NaN
8     NaN  NaN     NaN  NaN  blue  파란색
9     NaN  NaN     NaN  NaN  navy   남색

In [15]:
# 열 이름을 {기존:새이름}으로 설정 뒤, 데이터프레임에 다시 저장
df_1.rename(columns={"색1": "색", "이름1":"이름"}, inplace=True)
df_2.rename(columns={"색2": "색", "이름2":"이름"}, inplace=True)
df_3.rename(columns={"색3": "색", "이름3":"이름"}, inplace=True)

# 기본값: 행 기준으로 결합
result_row = pd.concat([df_1, df_2, df_3])

# 인덱스 값 확인 필요
display([df_1, df_2, df_3, result_row], ['df_1', 'df_2', 'df_3', 'result_row'])

[        색   이름
 0     red  빨간색
 1  orange  주황색,         색   이름
 2  yellow  노란색
 3   green  초록색,       색   이름
 8  blue  파란색
 9  navy   남색,         색   이름
 0     red  빨간색
 1  orange  주황색
 2  yellow  노란색
 3   green  초록색
 8    blue  파란색
 9    navy   남색]

['df_1', 'df_2', 'df_3', 'result_row']

In [21]:
# ignore_index = True 설정
result_row = pd.concat([df_1, df_2, df_3], ignore_index=True)

# 인덱스 값 확인 필요
display(df_1, df_2, df_3, result_row)

        색   이름
0     red  빨간색
1  orange  주황색

        색   이름
2  yellow  노란색
3   green  초록색

      색   이름
8  blue  파란색
9  navy   남색

        색   이름
0     red  빨간색
1  orange  주황색
2  yellow  노란색
3   green  초록색
4    blue  파란색
5    navy   남색

In [26]:
# 가로로 데이터를 연결하는 방법
df_1 = pd.DataFrame({'색': ['red', 'orange'],
                     '이름': ['빨간색', '주황색']},
                     index=[0, 1])

df_2 = pd.DataFrame({'색': ['yellow', 'green'],
                     '이름': ['노란색', '초록색']},
                    index=[2, 3])

df_3 = pd.DataFrame({'색': ['blue', 'navy'],
                     '이름': ['파란색', '남색']},
                    index=[8, 9])

# axis = 1 열 방향을 합치기
result_col = pd.concat([df_1, df_2, df_3], axis = 1)

# 연결하려는 데이터
display(df_1, df_2, df_3)

# 결과 데이터프레임
result_col

        색   이름
0     red  빨간색
1  orange  주황색

        색   이름
2  yellow  노란색
3   green  초록색

      색   이름
8  blue  파란색
9  navy   남색

        색   이름       색   이름     색   이름
0     red  빨간색     NaN  NaN   NaN  NaN
1  orange  주황색     NaN  NaN   NaN  NaN
2     NaN  NaN  yellow  노란색   NaN  NaN
3     NaN  NaN   green  초록색   NaN  NaN
8     NaN  NaN     NaN  NaN  blue  파란색
9     NaN  NaN     NaN  NaN  navy   남색

In [32]:
# 기존 인덱스 값을 지우고(drop=True), 0부터 다시 시작
df_2.reset_index(drop=True, inplace=True)
df_3.reset_index(drop=True, inplace=True)

result_col = pd.concat([df_1, df_2, df_3], axis = 1, ignore_index=False)

# 연결하려는 데이터
display(df_1, df_2, df_3)

# 결과 데이터 프레임
result_col

        색   이름
0     red  빨간색
1  orange  주황색

        색   이름
0  yellow  노란색
1   green  초록색

      색   이름
0  blue  파란색
1  navy   남색

        색   이름       색   이름     색   이름
0     red  빨간색  yellow  노란색  blue  파란색
1  orange  주황색   green  초록색  navy   남색

In [33]:
result_col["이름"]

    이름   이름   이름
0  빨간색  노란색  파란색
1  주황색  초록색   남색

In [34]:
# 열 이름을 {기존: 새이름}으로 설정 뒤, 데이터프레임에 다시 저장(inplace=True)
df_1.rename(columns={"색": "색1", "이름": "이름1"}, inplace=True)
df_2.rename(columns={"색": "색2", "이름": "이름2"}, inplace=True)
df_3.rename(columns={"색": "색3", "이름": "이름3"}, inplace=True)

result_col = pd.concat([df_1, df_2, df_3], axis=1)

# 연결하려는 데이터
display(df_1, df_2, df_3)

# 결과 데이터프레임
result_col

       색1  이름1
0     red  빨간색
1  orange  주황색

       색2  이름2
0  yellow  노란색
1   green  초록색

     색3  이름3
0  blue  파란색
1  navy   남색

       색1  이름1      색2  이름2    색3  이름3
0     red  빨간색  yellow  노란색  blue  파란색
1  orange  주황색   green  초록색  navy   남색

In [35]:
# append: axis=0 (세로)
df_1 = pd.DataFrame({'색': ['red', 'oragne'],
                     '이름': ['빨간색', '주황색']},
                    index=[0, 1])

df_2 = pd.DataFrame({'색': ['yellow', 'green'],
                     '이름': ['노란색', '초록색']},
                    index=[2, 3])

df_3 = pd.DataFrame({'색': ['blue', 'navy'],
                     '이름': ['파란색', '남색']},
                    index=[8, 9])

# index 값을 초기화하여 데이터 연결
result_append = df_1.append([df_2, df_3], ignore_index=True)

display(df_1, df_2, df_3, result_append)

        색   이름
0     red  빨간색
1  oragne  주황색

        색   이름
2  yellow  노란색
3   green  초록색

      색   이름
8  blue  파란색
9  navy   남색

        색   이름
0     red  빨간색
1  oragne  주황색
2  yellow  노란색
3   green  초록색
4    blue  파란색
5    navy   남색

In [37]:
# add_row라는 Series 생성
add_row = pd.Series(['purple', '보라색'], index=['색', '이름'])
print('>>> add_row 배열\n', add_row)
print('>>> 색 이름 출력:', add_row["색"])

# result_append에 .concat()을 이용해 add_row 추가
added_concat = pd.concat([result_append, add_row], ignore_index=True)

# result_append에 .append()를 이용해 add_row 추가
added_append = result_append.append(add_row, ignore_index=True)

# result_append, concat 사용, append 사용했을 때 결괏값 출력
display(result_append, added_concat, added_append)

>>> add_row 배열
 색     purple
이름       보라색
dtype: object
>>> 색 이름 출력: purple

        색   이름
0     red  빨간색
1  oragne  주황색
2  yellow  노란색
3   green  초록색
4    blue  파란색
5    navy   남색

        색   이름       0
0     red  빨간색     NaN
1  oragne  주황색     NaN
2  yellow  노란색     NaN
3   green  초록색     NaN
4    blue  파란색     NaN
5    navy   남색     NaN
6     NaN  NaN  purple
7     NaN  NaN     보라색

        색   이름
0     red  빨간색
1  oragne  주황색
2  yellow  노란색
3   green  초록색
4    blue  파란색
5    navy   남색
6  purple  보라색

In [38]:
# 네스티드 리스트(Nested list), list_ex 생성
list_ex=[['red', '빨간색']]

# list_ex에 다른 리스트 추가
list_ex.append(['orange', '주황색'])

# list_ex 출력
print('list_ex', list_ex)
print('list_ex의 첫번째 값', list_ex[0])
print('list_ex의 두번째 값', list_ex[1])

# list_ex를 데이터프레임으로 전환
df_list_ex = pd.DataFrame(list_ex, columns=['색', '이름'])
df_list_ex

list_ex [['red', '빨간색'], ['orange', '주황색']]
list_ex의 첫번째 값 ['red', '빨간색']
list_ex의 두번째 값 ['orange', '주황색']

        색   이름
0     red  빨간색
1  orange  주황색

In [39]:
pd.concat([list_ex])

TypeError: ignored